### ISSUE TITLE
Fix services declaration

### ISSUE THREAD

**Issue by acacopardo** [objective-php/services-factory#7]
We can't declare service id with notation foo::class
The @Inject can't found Foo::class

```
    new Service([
        'id' => Foo::class,
        'class' => Foo::class
    ])

    /**
     * @var Foo
     * @Inject(service="My\Namespace\Foo")
     */
    protected $foo;
```

I get
```
ObjectivePHP\ServicesFactory\Exception\Exception
Dependent service "My\Namespace\Foo" is not registered
```

If i set directly  ` 'id' => 'My\Namespace\Foo',` => same issue

**Comment by acacopardo** [comment]
`$serviceId = Str::cast($serviceSpecs->getId())->lower();`
On ServicesFactory Line 278

Lower method set namespace class in lower case.

**Comment by gauthier** [comment]
@acacopardo this workaround you found is ok, but is still a workaround :) this is definitely a bug, since we normalize service ids when registering services but not when requesting them. I just fixed it in dev, and will push a new release within minutes. Thanks for having reporting that!
